<?xml version="1.0" encoding="utf-8"?><Database Name="SchoolErpSystem" Class="LinqDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-J3DHBNP\;Initial Catalog=SchoolErpSystem;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="SchoolErpSystem" Provider="System.Data.SqlClient" />
  <Function Name="dbo.updateSubject" Method="updateSubject">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="Subject" Parameter="subject" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Class" Parameter="class" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.CrudSubject" Method="CrudSubject">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="Subject" Parameter="subject" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Class" Parameter="class" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="CrudOption" Parameter="crudOption" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="CrudSubjectResult">
      <Column Name="SubjectID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Subject" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Classes" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.crudemp" Method="crudemp">
    <Parameter Name="id" Type="System.Int32" DbType="Int" />
    <Parameter Name="Empname" Parameter="empname" Type="System.String" DbType="NVarChar(150)" />
    <Parameter Name="Email" Parameter="email" Type="System.String" DbType="NVarChar(150)" />
    <Parameter Name="Salary" Parameter="salary" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="CrudOption" Parameter="crudOption" Type="System.String" DbType="VarChar(50)" />
    <ElementType Name="crudempResult">
      <Column Name="Empid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Empname" Type="System.String" DbType="VarChar(150)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Salary" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.getStaffwithID" Method="getStaffwithID">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <ElementType Name="getStaffwithIDResult">
      <Column Name="StaffID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Designation" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="StaffType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Firstname" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Lastname" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Phone1" Type="System.Decimal" DbType="Decimal(12,0) NOT NULL" CanBeNull="false" />
      <Column Name="Phone2" Type="System.Decimal" DbType="Decimal(12,0)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="DateOfAppointment" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="Nationality" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Address" Type="System.String" DbType="VarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="HighestQualification" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="YearOfExperience" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PreviouseOrganization" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Image" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>