//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolERPSYSTEM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassType
    {
        public ClassType()
        {
            this.Subjects = new HashSet<Subject>();
            this.ClassLevels = new HashSet<ClassLevel>();
            this.FeeStructures = new HashSet<FeeStructure>();
            this.StudentTbles = new HashSet<StudentTble>();
        }
    
        public int ClassTypeID { get; set; }
        public string ClassType1 { get; set; }
    
        public virtual ICollection<Subject> Subjects { get; set; }
        public virtual ICollection<ClassLevel> ClassLevels { get; set; }
        public virtual ICollection<FeeStructure> FeeStructures { get; set; }
        public virtual ICollection<StudentTble> StudentTbles { get; set; }
    }
}
