//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolERPSYSTEM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassLevel
    {
        public ClassLevel()
        {
            this.FeeStructures = new HashSet<FeeStructure>();
            this.StudentTbles = new HashSet<StudentTble>();
        }
    
        public int LevelID { get; set; }
        public string Levelname { get; set; }
        public int Section { get; set; }
    
        public virtual ClassType ClassType { get; set; }
        public virtual ICollection<FeeStructure> FeeStructures { get; set; }
        public virtual ICollection<StudentTble> StudentTbles { get; set; }
    }
}
