//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolERPSYSTEM.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
   
    using System.Linq;
    
    public partial class SchoolErpSystemEntities : DbContext
    {
        public SchoolErpSystemEntities()
            : base("name=SchoolErpSystemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<ClassType> ClassTypes { get; set; }
        public DbSet<Subject> Subjects { get; set; }
        public DbSet<TblSession> TblSessions { get; set; }
        public DbSet<ClassLevel> ClassLevels { get; set; }
        public DbSet<FeeType> FeeTypes { get; set; }
        public DbSet<FeeStructure> FeeStructures { get; set; }
        public DbSet<tblCity> tblCities { get; set; }
        public DbSet<tblCountry> tblCountries { get; set; }
        public DbSet<tblState> tblStates { get; set; }
        public DbSet<StudentTble> StudentTbles { get; set; }
        public DbSet<Designation> Designations { get; set; }
        public DbSet<StaffType> StaffTypes { get; set; }
        public DbSet<AutoID> AutoIDs { get; set; }
    
       
    }
}
