//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolERPSYSTEM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentTble
    {
        public int ID { get; set; }
        public string AdmissionNo { get; set; }
        public string Firstname { get; set; }
        public string middlename { get; set; }
        public string Lastname { get; set; }
        public System.DateTime DOB { get; set; }
        public Nullable<int> Nationality { get; set; }
        public string LocalGov { get; set; }
        public string Gender { get; set; }
        public string Religion { get; set; }
        public int Section { get; set; }
        public int ClassLevel { get; set; }
        public string ClassAlphabet { get; set; }
        public System.DateTime AdmissionDate { get; set; }
        public string Fathername { get; set; }
        public string FatherOccupation { get; set; }
        public string Mothersname { get; set; }
        public string Mothersoccupation { get; set; }
        public string Fatherno { get; set; }
        public string Fathersemail { get; set; }
        public string Mothersno { get; set; }
        public string mothersEmail { get; set; }
        public string StudentNo { get; set; }
        public string StudentEmail { get; set; }
        public string Address { get; set; }
    
        public virtual ClassLevel ClassLevel1 { get; set; }
        public virtual ClassType ClassType { get; set; }
        public virtual tblCountry tblCountry { get; set; }
    }
}
