//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolERPSYSTEM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCountry
    {
        public tblCountry()
        {
            this.tblStates = new HashSet<tblState>();
            this.StudentTbles = new HashSet<StudentTble>();
        }
    
        public int CID { get; set; }
        public string Cname { get; set; }
    
        public virtual ICollection<tblState> tblStates { get; set; }
        public virtual ICollection<StudentTble> StudentTbles { get; set; }
    }
}
