//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SchoolERPSYSTEM.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblSession
    {
        public int SessionID { get; set; }
        public string Session { get; set; }
        public string Term { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
